"""Fix user column name

Revision ID: 4a5c41c0ec7b
Revises: 8cda293bafd8
Create Date: 2024-10-03 12:59:10.686009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a5c41c0ec7b'
down_revision: Union[str, None] = '8cda293bafd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_url', sa.String(), nullable=True))
    op.drop_column('users', 'imageUrl')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('imageUrl', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'image_url')
    # ### end Alembic commands ###
