"""Updating chat

Revision ID: 8dda372a8a7c
Revises: ddd06e7f3de9
Create Date: 2024-10-08 13:20:56.494724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dda372a8a7c'
down_revision: Union[str, None] = 'ddd06e7f3de9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_participants',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'chat_id')
    )
    op.add_column('messages', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('messages', sa.Column('chat_id', sa.Integer(), nullable=False))
    op.drop_constraint('messages_to_user_id_fkey', 'messages', type_='foreignkey')
    op.drop_constraint('messages_from_user_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'users', ['user_id'], ['id'])
    op.drop_column('messages', 'to_user_id')
    op.drop_column('messages', 'from_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('from_user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('to_user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_from_user_id_fkey', 'messages', 'users', ['from_user_id'], ['id'])
    op.create_foreign_key('messages_to_user_id_fkey', 'messages', 'users', ['to_user_id'], ['id'])
    op.drop_column('messages', 'chat_id')
    op.drop_column('messages', 'user_id')
    op.drop_table('chat_participants')
    op.drop_table('chats')
    # ### end Alembic commands ###
